CREATE DATABASE Senatur_Manha

USE Senatur_Manha

CREATE TABLE USUARIOS(
	UsuarioId INT IDENTITY PRIMARY KEY,
	Email VARCHAR(150) NOT NULL,
	Senha  VARCHAR(150) NOT NULL,
	TipoUsuario BIT NOT NULL
);

CREATE TABLE PACOTES(
	PacoteId INT IDENTITY PRIMARY KEY,
	NomePacote VARCHAR(150) NOT NULL,
	Descricao TEXT NOT NULL,
	DataIda DATE,
	DataVolta DATE,
	Valor MONEY NOT NULL,
	Ativo BIT,
	NomeCidade VARCHAR(150) 
);

DROP TABLE USUARIOS